server:
  port: 7772

eureka:
  instance:
    hostname: localhost
    # https://cloud.spring.io/spring-cloud-netflix/reference/html/#spring-cloud-eureka-server-prefer-ip-address
    prefer-ip-address: false
    preferIpAddress: false
  renewalPercentThreshold: 0.33
  # standalone mode
  client:
    registerWithEureka: false
    fetchRegistry: false
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/
spring:
  cloud:
  inetutils:
    ignored-interfaces:
      - lo0
      - gif0
      - stf0
      - en5
      - ap1
      - en4
      - en3
      - en2
      - en1
      - awdl0
      - llw0
      - bridge0
      - utun0
      - utun1
      - utun2